class GeneratedPredictionTable:
    def __init__(self):
        self.t = [
            '->',
            ';',
            '|',
            ',',
            'KW_NT',
            'KW_T',
            'KW_AXIOM',
            'ident',
            'term',
            'KW_EPSILON']
        self.nt = [
            'Program',
            'NT_Decl',
            'NT_Add',
            'T_Decl',
            'T_Add',
            'A_Decl',
            'RuleList',
            'Rule',
            'RuleResult',
            'RuleResultTail',
            'Chain']
        self.table = {('A_Decl', 'KW_AXIOM'): ['KW_AXIOM', 'ident', ';'],
                      ('Chain', ';'): [],
                      ('Chain', 'KW_EPSILON'): ['KW_EPSILON'],
                      ('Chain', 'ident'): ['ident', 'Chain'],
                      ('Chain', 'term'): ['term', 'Chain'],
                      ('Chain', '|'): [],
                      ('NT_Add', ','): [',', 'ident', 'NT_Add'],
                      ('NT_Add', ';'): [],
                      ('NT_Decl', 'KW_NT'): ['KW_NT', 'ident', 'NT_Add', ';'],
                      ('Program', 'KW_NT'): ['NT_Decl', 'T_Decl', 'RuleList', 'A_Decl'],
                      ('Rule', 'ident'): ['ident', '->', 'RuleResult', ';'],
                      ('RuleList', 'KW_AXIOM'): [],
                      ('RuleList', 'ident'): ['Rule', 'RuleList'],
                      ('RuleResult', ';'): ['Chain', 'RuleResultTail'],
                      ('RuleResult', 'KW_EPSILON'): ['Chain', 'RuleResultTail'],
                      ('RuleResult', 'ident'): ['Chain', 'RuleResultTail'],
                      ('RuleResult', 'term'): ['Chain', 'RuleResultTail'],
                      ('RuleResult', '|'): ['Chain', 'RuleResultTail'],
                      ('RuleResultTail', ';'): [],
                      ('RuleResultTail', '|'): ['|', 'RuleResult'],
                      ('T_Add', ','): [',', 'term', 'T_Add'],
                      ('T_Add', ';'): [],
                      ('T_Decl', 'KW_T'): ['KW_T', 'term', 'T_Add', ';']}
