class LR1:
    def __init__(self):
        self.action = {
            (0, 'KW_NT'): 's1',
            (1, 'ident'): 's4',
            (2, 'END'): 'f',
            (3, 'KW_T'): 's5',
            (4, ','): 's7',
            (4, ';'): ['r', 'NT_Add', 'ε'],
            (5, 'term'): 's9',
            (6, 'ident'): 's10',
            (6, 'KW_AXIOM'): ['r', 'RuleList', 'ε'],
            (7, 'ident'): 's13',
            (8, ';'): 's14',
            (9, ','): 's15',
            (9, ';'): ['r', 'T_Add', 'ε'],
            (10, '->'): 's17',
            (11, 'KW_AXIOM'): 's18',
            (12, 'ident'): 's10',
            (12, 'KW_AXIOM'): ['r', 'RuleList', 'ε'],
            (13, ','): 's7',
            (13, ';'): ['r', 'NT_Add', 'ε'],
            (14, 'KW_T'): ['r', 'NT_Decl', ['non-terminal', 'ident', 'NT_Add', ';']],
            (15, 'term'): 's22',
            (16, ';'): 's23',
            (17, 'KW_EPSILON'): 's26',
            (17, 'ident'): 's24',
            (17, 'term'): 's25',
            (17, ';'): ['r', 'Chain', 'ε'],
            (17, '|'): ['r', 'Chain', 'ε'],
            (18, 'ident'): 's29',
            (19, 'END'): ['r', 'Program', ['NT_Decl', 'T_Decl', 'RuleList', 'A_Decl']],
            (20, 'KW_AXIOM'): ['r', 'RuleList', ['Rule', 'RuleList']],
            (21, ';'): ['r', 'NT_Add', [',', 'ident', 'NT_Add']],
            (22, ','): 's15',
            (22, ';'): ['r', 'T_Add', 'ε'],
            (23, 'KW_AXIOM'): ['r', 'T_Decl', ['terminal', 'term', 'T_Add', ';']],
            (23, 'ident'): ['r', 'T_Decl', ['terminal', 'term', 'T_Add', ';']],
            (24, 'KW_EPSILON'): 's26',
            (24, 'ident'): 's24',
            (24, 'term'): 's25',
            (24, ';'): ['r', 'Chain', 'ε'],
            (24, '|'): ['r', 'Chain', 'ε'],
            (25, 'KW_EPSILON'): 's26',
            (25, 'ident'): 's24',
            (25, 'term'): 's25',
            (25, ';'): ['r', 'Chain', 'ε'],
            (25, '|'): ['r', 'Chain', 'ε'],
            (26, ';'): ['r', 'Chain', ['kwepsilon']],
            (26, '|'): ['r', 'Chain', ['kwepsilon']],
            (27, ';'): 's33',
            (28, '|'): 's34',
            (28, ';'): ['r', 'RuleResultTail', 'ε'],
            (29, ';'): 's36',
            (30, ';'): ['r', 'T_Add', [',', 'term', 'T_Add']],
            (31, ';'): ['r', 'Chain', ['ident', 'Chain']],
            (31, '|'): ['r', 'Chain', ['ident', 'Chain']],
            (32, ';'): ['r', 'Chain', ['term', 'Chain']],
            (32, '|'): ['r', 'Chain', ['term', 'Chain']],
            (33, 'KW_AXIOM'): ['r', 'Rule', ['ident', '->', 'RuleResult', ';']],
            (33, 'ident'): ['r', 'Rule', ['ident', '->', 'RuleResult', ';']],
            (34, 'KW_EPSILON'): 's26',
            (34, 'ident'): 's24',
            (34, 'term'): 's25',
            (34, ';'): ['r', 'Chain', 'ε'],
            (34, '|'): ['r', 'Chain', 'ε'],
            (35, ';'): ['r', 'RuleResult', ['Chain', 'RuleResultTail']],
            (36, 'END'): ['r', 'A_Decl', ['axiom', 'ident', ';']],
            (37, ';'): ['r', 'RuleResultTail', ['|', 'RuleResult']],
        }

        self.goto = {
            (0, 'NT_Decl'): 3,
            (0, 'Program'): 2,
            (3, 'T_Decl'): 6,
            (4, 'NT_Add'): 8,
            (6, 'RuleList'): 11,
            (6, 'Rule'): 12,
            (9, 'T_Add'): 16,
            (11, 'A_Decl'): 19,
            (12, 'Rule'): 12,
            (12, 'RuleList'): 20,
            (13, 'NT_Add'): 21,
            (17, 'RuleResult'): 27,
            (17, 'Chain'): 28,
            (22, 'T_Add'): 30,
            (24, 'Chain'): 31,
            (25, 'Chain'): 32,
            (28, 'RuleResultTail'): 35,
            (34, 'RuleResult'): 37,
            (34, 'Chain'): 28,
        }
