class LR1:
    def __init__(self):
        self.action = {
            (0, 'non-terminal'): 's1',
            (1, 'KW_NT'): 's4',
            (2, 'END'): 'f',
            (3, 'terminal'): 's5',
            (4, ','): 's7',
            (5, 'KW_T'): 's9',
            (6, 'KW_NT'): 's10',
            (7, 'KW_NT'): 's13',
            (8, ';'): 's14',
            (9, ','): 's15',
            (10, '->'): 's17',
            (11, 'axiom'): 's18',
            (12, 'KW_NT'): 's10',
            (13, ','): 's7',
            (14, 'terminal'): ['r', 'NT_Decl', ["'non-terminal'", 'ident', 'NT_Add', "';'"]],
            (15, 'KW_T'): 's22',
            (16, ';'): 's23',
            (17, 'KW_NT'): 's24',
            (17, 'KW_EPSILON'): 's26',
            (17, 'KW_T'): 's25',
            (18, 'KW_NT'): 's29',
            (19, 'END'): ['r', 'Program', ['NT_Decl', 'T_Decl', 'RuleList', 'A_Decl']],
            (20, 'axiom'): ['r', 'RuleList', ['Rule', 'RuleList']],
            (21, ';'): ['r', 'NT_Add', ["','", 'ident', 'NT_Add']],
            (22, ','): 's15',
            (23, 'KW_NT'): ['r', 'T_Decl', ["'terminal'", 'term', 'T_Add', "';'"]],
            (23, 'axiom'): ['r', 'T_Decl', ["'terminal'", 'term', 'T_Add', "';'"]],
            (24, 'KW_NT'): 's24',
            (24, 'KW_EPSILON'): 's26',
            (24, 'KW_T'): 's25',
            (25, 'KW_NT'): 's24',
            (25, 'KW_EPSILON'): 's26',
            (25, 'KW_T'): 's25',
            (26, '|'): ['r', 'Chain', ['kwepsilon']],
            (26, ';'): ['r', 'Chain', ['kwepsilon']],
            (27, ';'): 's33',
            (28, '|'): 's34',
            (29, ';'): 's36',
            (30, ';'): ['r', 'T_Add', ["','", 'term', 'T_Add']],
            (31, '|'): ['r', 'Chain', ['ident', 'Chain']],
            (31, ';'): ['r', 'Chain', ['ident', 'Chain']],
            (32, '|'): ['r', 'Chain', ['term', 'Chain']],
            (32, ';'): ['r', 'Chain', ['term', 'Chain']],
            (33, 'axiom'): ['r', 'Rule', ['ident', "'->'", 'RuleResult', "';'"]],
            (33, 'KW_NT'): ['r', 'Rule', ['ident', "'->'", 'RuleResult', "';'"]],
            (34, 'KW_NT'): 's24',
            (34, 'KW_EPSILON'): 's26',
            (34, 'KW_T'): 's25',
            (35, ';'): ['r', 'RuleResult', ['Chain', 'RuleResultTail']],
            (36, 'END'): ['r', 'A_Decl', ["'axiom'", 'ident', "';'"]],
            (37, ';'): ['r', 'RuleResultTail', ["'|'", 'RuleResult']],
            (38, ';'): ['r', 'NT_Add', ['eps']],
            (39, 'axiom'): ['r', 'RuleList', ['eps']],
            (40, ';'): ['r', 'T_Add', ['eps']],
            (41, ';'): ['r', 'Chain', ['eps']],
            (41, '|'): ['r', 'Chain', ['eps']],
            (42, ';'): ['r', 'RuleResultTail', ['eps']],
        }

        self.goto = {
            (0, 'Program'): 2,
            (0, 'NT_Decl'): 3,
            (3, 'T_Decl'): 6,
            (4, 'NT_Add'): 8,
            (6, 'Rule'): 12,
            (6, 'RuleList'): 11,
            (9, 'T_Add'): 16,
            (11, 'A_Decl'): 19,
            (12, 'Rule'): 12,
            (12, 'RuleList'): 20,
            (13, 'NT_Add'): 21,
            (17, 'RuleResult'): 27,
            (17, 'Chain'): 28,
            (22, 'T_Add'): 30,
            (24, 'Chain'): 31,
            (25, 'Chain'): 32,
            (28, 'RuleResultTail'): 35,
            (34, 'Chain'): 28,
            (34, 'RuleResult'): 37,
        }
